### ISSUE TITLE
Only works on first run with Windows

### ISSUE THREAD

**Issue by one-new-message** [cuppa-joe/dsame#7]
With the Windows application, dsame only works when "Start dsame" is checked after the installer runs. When this is checked, dsame runs just fine. When launched any other way, dsame does not do anything. I can display help text through cmd, but not actually decode anything.

Any ideas for what to try?

Thanks in advance.

(By the way, when this application works, it works REALLY WELL. Thank you for making such a great application open source!)

**Comment by A-c0rN** [comment]
If you run Dsame.py in the command prompt, it should solve your problem. Instead of doing "Start Dsame" do "Dsame.py [ARGS]"

**Comment by one-new-message** [comment]
I have not used this application in quite a long time; in fact, I do not remember authoring this thread.
I am certain that it will work correctly if I start the application from the command line through Python, but I do not have anything configured to test it.

I will close the issue, as it is no longer relevant.
